// <auto-generated />
using System;
using FactCloudAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactCloudAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260213023723_Historial")]
    partial class Historial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactCloudAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadEconomicaCIIU")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AutoretenedorRenta")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CiudadCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartamentoCodigo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("DigitoVerificacion")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RegimenFiscal")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegimenTributario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RetenedorICA")
                        .HasColumnType("bit");

                    b.Property<bool>("RetenedorIVA")
                        .HasColumnType("bit");

                    b.Property<bool>("RetenedorRenta")
                        .HasColumnType("bit");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cupones.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxUsos")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("UsosCodigo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("Cupones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "WELCOMEFC",
                            DescuentoPorcentaje = 20m,
                            IsActive = true,
                            MaxUsos = 30,
                            UsosCodigo = 0
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "FACTCLOUDPRO",
                            DescuentoPorcentaje = 30m,
                            IsActive = true,
                            MaxUsos = 30,
                            PlanId = 3,
                            UsosCodigo = 0
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "STARTEFC25",
                            DescuentoPorcentaje = 12m,
                            IsActive = true,
                            MaxUsos = 20,
                            PlanId = 1,
                            UsosCodigo = 0
                        });
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cupones.CuponUso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CuponId")
                        .HasColumnType("int");

                    b.Property<decimal>("DescuentoAplicado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SuscripcionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsadoAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CuponId");

                    b.HasIndex("SuscripcionId");

                    b.ToTable("CuponUso");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductoId1")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarifaINC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TarifaIVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ValorDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ProductoId1");

                    b.ToTable("DetalleFacturas");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleNotaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NotaCreditoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unidad");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotaCreditoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleNotaCredito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleNotaDebito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NotaDebitoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal>("SubtotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TarifaIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalLinea")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Unidad");

                    b.Property<decimal>("ValorDescuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorIVA")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotaDebitoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleNotaDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DocumentoSoporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUDS")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<int>("Consecutivo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoDian")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaRespuestaDian")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MensajeDian")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroRespuestaDian")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorCiudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorDepartamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorDireccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProveedorEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProveedorNit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProveedorNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProveedorTelefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProveedorTipoIdentificacion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RutaPDF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaXML")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DocumentosSoporte");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Cufe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("DiasCredito")
                        .HasColumnType("int");

                    b.Property<bool>("EnviadaCliente")
                        .HasColumnType("bit");

                    b.Property<bool>("EnviadaDIAN")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioCliente")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvioDIAN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimiteEnvioDIAN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoraEmision")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MedioPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("MontoPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Prefijo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QRCode")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RespuestaDIAN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDescuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFactura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalRetenciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("XmlBase64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FormaPagoNotaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Efectivo");

                    b.Property<int>("NotaCreditoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotaCreditoId");

                    b.ToTable("FormasPagoNotaCredito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FormaPagoNotaDebito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Efectivo");

                    b.Property<int>("NotaDebitoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NotaDebitoId");

                    b.ToTable("FormasPagoNotaDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FotoPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UrlExterna")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("FotoPerfils");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUFE")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoDIAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ReteICA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("devolucion");

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("XMLBase64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Estado");

                    b.HasIndex("FacturaId");

                    b.HasIndex("FechaElaboracion");

                    b.HasIndex("NumeroNota");

                    b.HasIndex("Tipo");

                    b.HasIndex("UsuarioId");

                    b.ToTable("NotasCredito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaDebito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CUFE")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("ClienteId1")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int?>("FacturaId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaElaboracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoDIAN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ReteICA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuentos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalINC")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalNeto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId1")
                        .HasColumnType("int");

                    b.Property<string>("XMLBase64")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ClienteId1");

                    b.HasIndex("Estado");

                    b.HasIndex("FacturaId");

                    b.HasIndex("FacturaId1");

                    b.HasIndex("FechaElaboracion");

                    b.HasIndex("NumeroNota");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("NotasDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Planes.PlanFacturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DescuentoActivo")
                        .HasColumnType("bit");

                    b.Property<int?>("DescuentoPorcentaje")
                        .HasColumnType("int");

                    b.Property<bool>("Destacado")
                        .HasColumnType("bit");

                    b.Property<int>("DuracionMeses")
                        .HasColumnType("int");

                    b.Property<int?>("LimiteDocumentosAnuales")
                        .HasColumnType("int");

                    b.Property<int?>("LimiteUsuarios")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioAnual")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PlanesFacturacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "STARTER",
                            Descripcion = "Ideal para emprendedores iniciando",
                            DescuentoActivo = true,
                            DescuentoPorcentaje = 15,
                            Destacado = false,
                            DuracionMeses = 12,
                            LimiteDocumentosAnuales = 30,
                            LimiteUsuarios = 1,
                            Nombre = "Starter",
                            PrecioAnual = 135000m
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "BASICO",
                            Descripcion = "Para pequeños negocios en crecimiento",
                            DescuentoActivo = true,
                            DescuentoPorcentaje = 10,
                            Destacado = false,
                            DuracionMeses = 12,
                            LimiteDocumentosAnuales = 140,
                            LimiteUsuarios = 1,
                            Nombre = "Básico",
                            PrecioAnual = 300000m
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "PROFESIONAL",
                            Descripcion = "Perfecto para PYMES establecidas",
                            DescuentoActivo = true,
                            DescuentoPorcentaje = 10,
                            Destacado = false,
                            DuracionMeses = 12,
                            LimiteDocumentosAnuales = 540,
                            LimiteUsuarios = 1,
                            Nombre = "Profesional",
                            PrecioAnual = 770000m
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "EMPRESARIAL",
                            Descripcion = "Solución completa para empresas grandes",
                            DescuentoActivo = true,
                            DescuentoPorcentaje = 15,
                            Destacado = false,
                            DuracionMeses = 12,
                            LimiteDocumentosAnuales = 1550,
                            LimiteUsuarios = 1,
                            Nombre = "Empresarial",
                            PrecioAnual = 1300000m
                        });
                });

            modelBuilder.Entity("FactCloudAPI.Models.Planes.PlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlanFacturacionId")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tooltip")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlanFacturacionId");

                    b.ToTable("PlanFeature");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlanFacturacionId = 1,
                            Texto = "1 Usuario",
                            Tooltip = "Cuenta individual para emprendedores que están empezando."
                        },
                        new
                        {
                            Id = 2,
                            PlanFacturacionId = 1,
                            Texto = "30 Documentos anuales",
                            Tooltip = "Emite hasta 30 facturas electrónicas al año."
                        },
                        new
                        {
                            Id = 3,
                            PlanFacturacionId = 1,
                            Texto = "Funciones básicas",
                            Tooltip = "Creación de facturas, gestión de clientes y productos. Reportes simples incluidos."
                        },
                        new
                        {
                            Id = 4,
                            PlanFacturacionId = 2,
                            Texto = "1 Usuario",
                            Tooltip = "Cuenta individual perfecta para emprendedores y negocios unipersonales.Acceso completo a todas las funciones."
                        },
                        new
                        {
                            Id = 5,
                            PlanFacturacionId = 2,
                            Texto = "140 Documentos electrónicos al año",
                            Tooltip = "Perfecto para negocios que emiten hasta 8 documentos diarios."
                        },
                        new
                        {
                            Id = 6,
                            PlanFacturacionId = 2,
                            Texto = "Funciones básicas",
                            Tooltip = "Creación de facturas, gestión de clientes, productos, notas débito y crédito. Reportes simples incluidos."
                        },
                        new
                        {
                            Id = 7,
                            PlanFacturacionId = 3,
                            Texto = "1 Usuario",
                            Tooltip = "Cuenta individual con acceso completo a todas las funcionalidades del sistema."
                        },
                        new
                        {
                            Id = 8,
                            PlanFacturacionId = 3,
                            Texto = "540 Documentos electrónicos al año",
                            Tooltip = "Ideal para PYMES que facturan de forma constante durante todo el año."
                        },
                        new
                        {
                            Id = 9,
                            PlanFacturacionId = 3,
                            Texto = "Facturación electrónica DIAN",
                            Tooltip = "Emisión de facturas electrónicas válidas ante la DIAN, cumpliendo la normativa vigente."
                        },
                        new
                        {
                            Id = 10,
                            PlanFacturacionId = 3,
                            Texto = "Notas crédito y débito",
                            Tooltip = "Corrección y ajustes de facturas mediante notas crédito y débito electrónicas."
                        },
                        new
                        {
                            Id = 11,
                            PlanFacturacionId = 3,
                            Texto = "Gestión avanzada de clientes y productos",
                            Tooltip = "Administra clientes, productos, precios e impuestos de forma organizada."
                        },
                        new
                        {
                            Id = 12,
                            PlanFacturacionId = 3,
                            Texto = "Reportes y control de facturación",
                            Tooltip = "Consulta reportes básicos de ventas, documentos emitidos y estado de facturación."
                        },
                        new
                        {
                            Id = 13,
                            PlanFacturacionId = 4,
                            Texto = "1 Usuario",
                            Tooltip = "Acceso completo al sistema con control total de la facturación empresarial."
                        },
                        new
                        {
                            Id = 14,
                            PlanFacturacionId = 4,
                            Texto = "1550 Documentos electrónicos al año",
                            Tooltip = "Pensado para empresas con alto volumen de facturación anual."
                        },
                        new
                        {
                            Id = 15,
                            PlanFacturacionId = 4,
                            Texto = "Facturación electrónica DIAN",
                            Tooltip = "Cumple con todos los requisitos exigidos por la DIAN para facturación electrónica."
                        },
                        new
                        {
                            Id = 16,
                            PlanFacturacionId = 4,
                            Texto = "Notas crédito y débito ilimitadas",
                            Tooltip = "Emite notas crédito y débito sin restricciones dentro del límite anual de documentos."
                        },
                        new
                        {
                            Id = 17,
                            PlanFacturacionId = 4,
                            Texto = "Gestión completa de clientes y productos",
                            Tooltip = "Control detallado de clientes, productos, impuestos y precios."
                        },
                        new
                        {
                            Id = 18,
                            PlanFacturacionId = 4,
                            Texto = "Reportes administrativos",
                            Tooltip = "Accede a reportes de ventas y facturación para control interno y contable."
                        },
                        new
                        {
                            Id = 19,
                            PlanFacturacionId = 4,
                            Texto = "Soporte prioritario",
                            Tooltip = "Atención prioritaria para resolución de dudas y soporte técnico."
                        });
                });

            modelBuilder.Entity("FactCloudAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BaseGravable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CantidadDisponible")
                        .HasColumnType("int");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodigoInterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoUNSPSC")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Costo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("GravaINC")
                        .HasColumnType("bit");

                    b.Property<string>("Marca")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ProductoExcluido")
                        .HasColumnType("bit");

                    b.Property<bool>("ProductoExento")
                        .HasColumnType("bit");

                    b.Property<decimal?>("RetencionFuente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetencionICA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RetencionIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TarifaINC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TarifaIVA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TipoImpuesto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoProducto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Sesiones.HistorialSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Dispositivo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Navegador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SesionActual")
                        .HasColumnType("bit");

                    b.Property<string>("SistemaOperativo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialSesiones");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Suscripciones.SuscripcionFacturacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("DocumentosUsados")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanFacturacionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanFacturacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SuscripcionesFacturacion");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaDesactivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FotoPerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroIdentificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoIdentificacion")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuarios.ConfiguracionDian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmbienteDIAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaVigenciaFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVigenciaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroResolucionDIAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrefijoAutorizadoDIAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangoNumeracionDesde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RangoNumeracionHasta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwarePIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareProveedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId")
                        .IsUnique();

                    b.ToTable("ConfiguracionesDian");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuarios.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActividadEconomicaCIIU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DvNit")
                        .HasColumnType("int");

                    b.Property<string>("Nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPersona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cliente", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cupones.Cupon", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Planes.PlanFacturacion", "PlanFacturacion")
                        .WithMany()
                        .HasForeignKey("PlanId");

                    b.Navigation("PlanFacturacion");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cupones.CuponUso", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Cupones.Cupon", "Cupon")
                        .WithMany("usos")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Suscripciones.SuscripcionFacturacion", "Suscripcion")
                        .WithMany()
                        .HasForeignKey("SuscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("Suscripcion");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleFactura", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Factura", "Factura")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Producto", null)
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("ProductoId1");

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleNotaCredito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.NotaCredito", "NotaCredito")
                        .WithMany("DetalleNotaCredito")
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaCredito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DetalleNotaDebito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.NotaDebito", "NotaDebito")
                        .WithMany("Detalles")
                        .HasForeignKey("NotaDebitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaDebito");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("FactCloudAPI.Models.DocumentoSoporte", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Factura", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FormaPagoNotaCredito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.NotaCredito", "NotaCredito")
                        .WithMany("FormasPago")
                        .HasForeignKey("NotaCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaCredito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FormaPagoNotaDebito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.NotaDebito", "NotaDebito")
                        .WithMany("FormasPago")
                        .HasForeignKey("NotaDebitoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.FotoPerfil", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithOne("FotoPerfil")
                        .HasForeignKey("FactCloudAPI.Models.FotoPerfil", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaCredito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FactCloudAPI.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaDebito", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FactCloudAPI.Models.Cliente", null)
                        .WithMany("NotasDebito")
                        .HasForeignKey("ClienteId1");

                    b.HasOne("FactCloudAPI.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Factura", null)
                        .WithMany("NotasDebito")
                        .HasForeignKey("FacturaId1");

                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Usuario", null)
                        .WithMany("NotasDebito")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Planes.PlanFeature", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Planes.PlanFacturacion", "PlanFacturacion")
                        .WithMany("Features")
                        .HasForeignKey("PlanFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanFacturacion");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Producto", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany("Productos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Sesiones.HistorialSesion", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Suscripciones.SuscripcionFacturacion", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Planes.PlanFacturacion", "PlanFacturacion")
                        .WithMany("Suscripciones")
                        .HasForeignKey("PlanFacturacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithMany("Suscripciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanFacturacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuarios.ConfiguracionDian", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuarios.Negocio", "Negocio")
                        .WithOne("ConfiguracionDIAN")
                        .HasForeignKey("FactCloudAPI.Models.Usuarios.ConfiguracionDian", "NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuarios.Negocio", b =>
                {
                    b.HasOne("FactCloudAPI.Models.Usuario", "Usuario")
                        .WithOne("Negocio")
                        .HasForeignKey("FactCloudAPI.Models.Usuarios.Negocio", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("NotasDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Cupones.Cupon", b =>
                {
                    b.Navigation("usos");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("NotasDebito");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaCredito", b =>
                {
                    b.Navigation("DetalleNotaCredito");

                    b.Navigation("FormasPago");
                });

            modelBuilder.Entity("FactCloudAPI.Models.NotaDebito", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("FormasPago");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Planes.PlanFacturacion", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Producto", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Facturas");

                    b.Navigation("FotoPerfil");

                    b.Navigation("Negocio")
                        .IsRequired();

                    b.Navigation("NotasDebito");

                    b.Navigation("Productos");

                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("FactCloudAPI.Models.Usuarios.Negocio", b =>
                {
                    b.Navigation("ConfiguracionDIAN")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
